[package]
name = "pubsub_zmq"
version = "0.1.0"
authors = ["yubo <anhuitianyu@163.com>"]
edition = "2018"

[dependencies.zmq]
version = "0.9"
default-features = false
features = []

[dependencies]
cita-logger = "0.1.1"
crossbeam-channel = "0.4"
lazy_static = "1.4"